return {
    version = "0.1.0-alpha.8",
    read_only = true,
    inventory_bags = { 0, 8, 10, 11, 12, 13, 14, 15, 16 },
    debounce_seconds = 0.25,
    maximum_debounce_seconds = 1.50,
    buff_refresh_seconds = 0.25,
    beam_width = 64,
    cache_schema_version = 2,
    weapon_policy_version = 1,
    manual_override_policy_version = 1,
    verified_item_policy = "Verified",
    manual_slots = {
        Main = true,
        Sub = true,
        Range = true,
        Ammo = true,
    },
    upgrade_candidate_limit = 100,
    upgrade_result_limit = 10,
    inventory_history_limit = 8,
    expected_verified_actions = 106,
    expected_mechanics_rows = 4,
};
