-- Generated by tools/generate_data.py.
-- Source: data/effects_source.json. Do not edit this file directly.

local data = {
    ["schema_version"] = 1,
    ["data_version"] = 1,
    ["effects"] = {
        {
            ["id"] = "E0001",
            ["item_id"] = 14928,
            ["category"] = "Utility",
            ["tag"] = "learn_blue_magic",
            ["stat"] = nil,
            ["value"] = nil,
            ["unit"] = "Unknown magnitude",
            ["applies_to"] = {
                "learning",
            },
            ["condition_type"] = "Equipped",
            ["condition_value"] = "Hands",
            ["verification"] = "Verified text; magnitude unknown",
            ["confidence"] = "high",
            ["verified_text"] = true,
            ["source_id"] = "S007",
            ["horizon_specific"] = false,
            ["notes"] = "Mandatory categorical Learn-set effect; contributes no numeric score.",
        },
        {
            ["id"] = "E0002",
            ["item_id"] = 15265,
            ["category"] = "Blue Magic",
            ["tag"] = "monster_correlation",
            ["stat"] = nil,
            ["value"] = nil,
            ["unit"] = "Unknown magnitude",
            ["applies_to"] = {
                "physical",
                "magical",
                "debuff",
            },
            ["condition_type"] = "Correlation applies",
            ["condition_value"] = "Favorable or unfavorable family relation",
            ["verification"] = "Verified text; magnitude unknown",
            ["confidence"] = "high",
            ["verified_text"] = true,
            ["source_id"] = "S007",
            ["horizon_specific"] = false,
            ["notes"] = "Conditional candidate only; target-family state is not inferred.",
        },
        {
            ["id"] = "E0003",
            ["item_id"] = 15684,
            ["category"] = "Defense",
            ["tag"] = nil,
            ["stat"] = "magic_defense_bonus",
            ["value"] = 1,
            ["unit"] = "Trait tier",
            ["applies_to"] = {
                "idle",
                "mdt",
            },
            ["condition_type"] = "Always",
            ["condition_value"] = nil,
            ["verification"] = "Verified",
            ["confidence"] = "high",
            ["verified_text"] = true,
            ["source_id"] = "S007",
            ["horizon_specific"] = true,
            ["notes"] = "Horizon-specific addition.",
        },
    },
};

data.by_item = {};
for _, effect in ipairs(data.effects) do
    data.by_item[effect.item_id] = data.by_item[effect.item_id] or {};
    table.insert(data.by_item[effect.item_id], effect);
end

return data;
