-- Generated by tools/generate_data.py.
-- Source: data/policies_source.json. Do not edit this file directly.

local data = {
    ["schema_version"] = 1,
    ["data_version"] = 4,
    ["jobs"] = {
        ["BLU"] = {
            ["default_context"] = "engaged",
            ["contexts"] = {
                ["engaged"] = {
                    ["label"] = "Engaged",
                    ["objectives"] = {
                        {
                            ["stat"] = "haste",
                            ["label"] = "Haste",
                            ["direction"] = "max",
                            ["cap"] = 25,
                        },
                        {
                            ["stat"] = "accuracy",
                            ["label"] = "Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "store_tp",
                            ["label"] = "Store TP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "attack",
                            ["label"] = "Attack",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "dex",
                            ["label"] = "DEX",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                    },
                },
                ["physical"] = {
                    ["label"] = "Blue Magic - Physical",
                    ["objectives"] = {
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "accuracy",
                            ["label"] = "Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "str",
                            ["label"] = "STR",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "dex",
                            ["label"] = "DEX",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "attack",
                            ["label"] = "Attack",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "vit",
                            ["label"] = "VIT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "agi",
                            ["label"] = "AGI",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "int",
                            ["label"] = "INT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "chr",
                            ["label"] = "CHR",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["magical"] = {
                    ["label"] = "Blue Magic - Magical",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_accuracy",
                            ["label"] = "Magic Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "magic_attack_bonus",
                            ["label"] = "Magic Attack Bonus",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "int",
                            ["label"] = "INT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "chr",
                            ["label"] = "CHR",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["debuff"] = {
                    ["label"] = "Blue Magic - Debuff",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_accuracy",
                            ["label"] = "Magic Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "int",
                            ["label"] = "INT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "chr",
                            ["label"] = "CHR",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["drain"] = {
                    ["label"] = "Blue Magic - Drain",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_accuracy",
                            ["label"] = "Magic Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "int",
                            ["label"] = "INT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "chr",
                            ["label"] = "CHR",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["healing"] = {
                    ["label"] = "Blue Magic - Healing",
                    ["objectives"] = {
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "vit",
                            ["label"] = "VIT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "cure_potency",
                            ["label"] = "Cure Potency",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["breath"] = {
                    ["label"] = "Blue Magic - Breath",
                    ["objectives"] = {
                        {
                            ["stat"] = "hp",
                            ["label"] = "Current HP Support",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "magic_accuracy",
                            ["label"] = "Magic Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                    },
                },
                ["buff"] = {
                    ["label"] = "Blue Magic - General Buff",
                    ["objectives"] = {
                        {
                            ["stat"] = "spell_interruption_down",
                            ["label"] = "Spell Interruption Down",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["buff_skill"] = {
                    ["label"] = "Blue Magic - Skill Buff",
                    ["objectives"] = {
                        {
                            ["stat"] = "blue_magic_skill",
                            ["label"] = "Blue Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mnd",
                            ["label"] = "MND",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "spell_interruption_down",
                            ["label"] = "Spell Interruption Down",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["learning"] = {
                    ["label"] = "Learning",
                    ["required_tags"] = {
                        "learn_blue_magic",
                    },
                    ["objectives"] = {
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "evasion",
                            ["label"] = "Evasion",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "magic_defense_bonus",
                            ["label"] = "Magic Defense Bonus",
                            ["direction"] = "max",
                        },
                    },
                },
                ["evasion"] = {
                    ["label"] = "Evasion",
                    ["objectives"] = {
                        {
                            ["stat"] = "evasion_skill",
                            ["label"] = "Evasion Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "evasion",
                            ["label"] = "Evasion",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "agi",
                            ["label"] = "AGI",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "physical_damage_taken",
                            ["label"] = "PDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["idle"] = {
                    ["label"] = "Idle",
                    ["objectives"] = {
                        {
                            ["stat"] = "refresh",
                            ["label"] = "Refresh",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "regen",
                            ["label"] = "Regen",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "physical_damage_taken",
                            ["label"] = "PDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "magic_damage_taken",
                            ["label"] = "MDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["pdt"] = {
                    ["label"] = "Physical Defense",
                    ["objectives"] = {
                        {
                            ["stat"] = "physical_damage_taken",
                            ["label"] = "PDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "evasion",
                            ["label"] = "Evasion",
                            ["direction"] = "max",
                        },
                    },
                },
                ["mdt"] = {
                    ["label"] = "Magic Defense",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_damage_taken",
                            ["label"] = "MDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "magic_defense_bonus",
                            ["label"] = "Magic Defense Bonus",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
            },
        },
        ["BLM"] = {
            ["default_context"] = "nuke",
            ["contexts"] = {
                ["nuke"] = {
                    ["label"] = "Nuke",
                    ["dynamic_balance"] = "blm_nuke",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_accuracy",
                            ["label"] = "Magic Accuracy",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "magic_attack_bonus",
                            ["label"] = "Magic Attack Bonus",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "int",
                            ["label"] = "INT",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "elemental_magic_skill",
                            ["label"] = "Elemental Magic Skill",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["fast_cast"] = {
                    ["label"] = "Fast Cast",
                    ["objectives"] = {
                        {
                            ["stat"] = "fast_cast",
                            ["label"] = "Fast Cast",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "spell_interruption_down",
                            ["label"] = "Spell Interruption Down",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["resting"] = {
                    ["label"] = "Resting",
                    ["objectives"] = {
                        {
                            ["stat"] = "hmp",
                            ["label"] = "hMP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "refresh",
                            ["label"] = "Refresh",
                            ["direction"] = "max",
                        },
                    },
                },
                ["idle"] = {
                    ["label"] = "Idle",
                    ["objectives"] = {
                        {
                            ["stat"] = "refresh",
                            ["label"] = "Refresh",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "physical_damage_taken",
                            ["label"] = "PDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "magic_damage_taken",
                            ["label"] = "MDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["pdt"] = {
                    ["label"] = "Physical Defense",
                    ["objectives"] = {
                        {
                            ["stat"] = "physical_damage_taken",
                            ["label"] = "PDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "defense",
                            ["label"] = "Defense",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                    },
                },
                ["mdt"] = {
                    ["label"] = "Magic Defense",
                    ["objectives"] = {
                        {
                            ["stat"] = "magic_damage_taken",
                            ["label"] = "MDT",
                            ["direction"] = "min",
                        },
                        {
                            ["stat"] = "magic_defense_bonus",
                            ["label"] = "Magic Defense Bonus",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "hp",
                            ["label"] = "HP",
                            ["direction"] = "max",
                        },
                        {
                            ["stat"] = "mp",
                            ["label"] = "MP",
                            ["direction"] = "max",
                        },
                    },
                },
            },
        },
    },
};


return data;
