#!/usr/bin/env python3
"""Generate deterministic Lua data snapshots from the reviewed JSON inputs."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

TARGETS = {
    "catalog_source.json": "catalog.lua",
    "effects_source.json": "effects.lua",
    "actions_source.json": "actions.lua",
    "mechanics_source.json": "mechanics.lua",
    "policies_source.json": "policies.lua",
    "sources.json": "sources.lua",
}


def lua_value(value: Any, depth: int = 0) -> str:
    indent = "    " * depth
    child = "    " * (depth + 1)
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        if not value:
            return "{}"
        rows = [child + lua_value(item, depth + 1) + "," for item in value]
        return "{\n" + "\n".join(rows) + "\n" + indent + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = [
            child + "[" + json.dumps(str(key), ensure_ascii=False) + "] = "
            + lua_value(item, depth + 1) + ","
            for key, item in value.items()
        ]
        return "{\n" + "\n".join(rows) + "\n" + indent + "}"
    raise TypeError(f"Unsupported value: {type(value)!r}")


def render(source_name: str, payload: dict[str, Any]) -> str:
    header = (
        "-- Generated by tools/generate_data.py.\n"
        f"-- Source: data/{source_name}. Do not edit this file directly.\n\n"
    )
    body = "local data = " + lua_value(payload) + ";\n\n"
    if source_name == "catalog_source.json":
        body += (
            "data.by_id = {};\n"
            "for _, item in ipairs(data.items) do\n"
            "    data.by_id[item.id] = item;\n"
            "end\n"
        )
    elif source_name == "effects_source.json":
        body += (
            "data.by_item = {};\n"
            "for _, effect in ipairs(data.effects) do\n"
            "    data.by_item[effect.item_id] = data.by_item[effect.item_id] or {};\n"
            "    table.insert(data.by_item[effect.item_id], effect);\n"
            "end\n"
        )
    elif source_name == "actions_source.json":
        body += (
            "data.by_id = {};\n"
            "data.by_name = {};\n"
            "for _, action in ipairs(data.actions) do\n"
            "    data.by_id[action.id] = action;\n"
            "    data.by_name[string.lower(action.name)] = action;\n"
            "end\n"
        )
    elif source_name == "mechanics_source.json":
        body += (
            "data.by_action = {};\n"
            "for _, mechanic in ipairs(data.mechanics) do\n"
            "    data.by_action[mechanic.action_id] = mechanic;\n"
            "end\n"
        )
    elif source_name == "sources.json":
        body += (
            "data.by_id = {};\n"
            "for _, source in ipairs(data.sources) do\n"
            "    data.by_id[source.id] = source;\n"
            "end\n"
        )
    return header + body + "\nreturn data;\n"


def render_all() -> dict[Path, str]:
    result: dict[Path, str] = {}
    for source_name, target_name in TARGETS.items():
        payload = json.loads((DATA / source_name).read_text(encoding="utf-8"))
        result[DATA / target_name] = render(source_name, payload)
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if committed Lua snapshots differ from the JSON inputs.",
    )
    args = parser.parse_args()

    stale: list[str] = []
    for target, expected in render_all().items():
        if args.check:
            actual = target.read_text(encoding="utf-8") if target.exists() else ""
            if actual != expected:
                stale.append(target.relative_to(ROOT).as_posix())
        else:
            target.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        print("Stale generated data: " + ", ".join(stale), file=sys.stderr)
        return 1
    if args.check:
        print("Generated Lua data matches reviewed JSON inputs.")
    else:
        print("Generated Lua data snapshots.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
